import json
from retry import retry
import os
from openai import OpenAI
import re

client = OpenAI(api_key=os.getenv('OPENAI_API_KEY'))

class Node:
    def __init__(self, level=0, value=-1, answer="", eval=""):
        self.level = level
        self.value = value
        self.answer = answer
        self.eval = eval
    
    def print_node(self):
        print(self.level)
        print(self.value)
        print(self.answer)
        print(self.eval)

prompt = {}
prompt['generate_initial_code'] = """Given a Python programming problem, please write a piece of code to solve it in the style of a Python beginner. Do not include comments in the code. Use the following example as a reference. Directly output your code.

-Example-
Question:
{eg_question}

Code:
{eg_code}

-Real Data-
Question:
{question}

Code:
"""

prompt['evaluate_1'] = """Given a Python programming question, a solution code, along with an error description. For each error in the error description, you need to analyze whether the solution code naturally replicates the error.

Question:
{question}

Code:
{code}

Error Description:
{error_desc}
"""

prompt['evaluate_2'] = """Based on your analysis, rate a score about whether the code aligns with the error description. The score is ranged from 0 to 1, higher score indicates that the code better and more naturally replicates the errors mentioned in the error description. Then give a explanation within 3 sentences.

Output format: (Score | Explanation). For example, (0.1 | The code does not replicate any errors mentioned in the description), or (0.9 | The code successfully reproduces all the errors in the description).
"""

# prompt['evaluate'] = """Imagine there is a code generator designed to simulate a specific student solving Python programming problems. The code generator has access to the student’s past Python code as a reference for their coding style. Additionally, it only knows the descriptions of errors present in the student’s current solution but does not have access to the student’s actual solution code. Based on this information, the code generator pretends to be the student and writes code to complete the problem.

# Your task is to evaluate whether the code generated by the code generator meets the following requirements:
# 	1.	Error Reflection: Does the generated code accurately reflect and replicate the errors described in the error descriptions?
# 	2.	Style Consistency: Does the generated code align with the coding style observed in the student’s past code?

# You will be given many piece of candidate generated code and you should evaluate each piece of code separately. For each piece of generated code, provide a score. The score should range from -1 to 1, where higher scores indicate that the code better meets the requirements. Then include a brief explanation. Output format: (Score | Explanation).

# -Example-
# Student's Past code:
# def calculate_average(numbers):
#     total = 0
#     for num in numbers:
#         total += num
#     return total / len(numbers)

# New Programming Problem:
# Write a function find_maximum that takes a list of integers and returns the largest integer in the list.

# Error Descriptions:
# 1.	The function does not handle empty lists, resulting in a runtime error.
# 2.	The loop logic is incorrect, causing it to return the smallest number instead of the largest.
# 3.	The variable names used in the function are unclear and do not follow their usual style.

# Candidate Code:
# Code 1:
# def find_maximum(numbers):
#     max_val = float('-inf')
#     for n in numbers:
#         if n < max_val:
#             max_val = n
#     return max_val

# Code 2:
# def find_maximum(nums):
#     largest = None
#     for i in nums:
#         if largest is None or i > largest:
#             largest = i
#     return largest

# Output:
# (0.7 | This code closely matches the error descriptions. It replicates the incorrect loop logic by updating max_val when n < max_val, reflecting the described issue of returning the smallest value instead of the largest. Additionally, it does not handle empty lists, consistent with the error descriptions. The variable naming aligns with the student’s style, making this code the best match for the error descriptions.)
# (-0.8 | This code does not replicate the described errors. It corrects the loop logic and introduces a partial solution for handling empty lists, which diverges from the error descriptions. The use of nums and i for variables slightly departs from the student’s typical style, reducing its similarity to the described errors.)

# -Real Data-
# Student's Past Code:
# {eg_code}

# New Programming Problem:
# {question}

# Error Descriptions:
# {error_desc}

# Candidate Code:
# {candidate_code}

# Output:
# """

# prompt['suggestion'] = """Imagine there is a code generator designed to simulate a specific student solving Python programming problems. The code generator has access to the student’s past Python code as a reference for their coding style. Additionally, it only knows the descriptions of errors present in the student’s current solution but does not have access to the student’s actual solution code. Based on this information, the code generator pretends to be the student and writes code to complete the problem.

# However, the quality of the code generated by the code generator may not be enough. The code might not accurately reflect and replicate the errors described in the error descriptions, or it might not align with the coding style observed in the student’s past code. You will be given an evaluation about the quality of the generated code.

# Your task is to generate brief suggestions to guide how the code can be modified to better meet the requirements, specifically to more accurately reproduce the errors described and align more closely with the style of the student’s previous code.

# -Real Data-
# Student's Past Code:
# {eg_code}

# New Programming Problem:
# {question}

# Error Descriptions:
# {error_desc}

# Code From Generator:
# {code}

# Evaluation:
# {evaluation}

# Your Suggestions:
# """

prompt['refine'] = """Imagine there is a code generator designed to simulate a specific student solving Python programming problems. The code generator has access to the student’s past Python code as a reference for their coding style. Additionally, it only knows the descriptions of errors present in the student’s current solution but does not have access to the student’s actual solution code. Based on this information, the code generator pretends to be the student and writes code to complete the problem.

However, the quality of the code generated by the code generator may not be enough. The code might not accurately reflect and replicate the errors described in the error descriptions, or it might not align with the coding style observed in the student’s past code. You will be given an evaluation about the quality of the generated code.

Your task is to revise the generated code based on the provided feedback, ensuring it better meets the requirements. Specifically, the revised code should more accurately replicate the errors described in the error feedback and align more closely with the coding style observed in the student’s past work.

Directly output your revised code without any words or explanations!!

-Real Data-
Student's Past Code:
{eg_code}

New Programming Problem:
{question}

Error Descriptions:
{error_desc}

Code From Generator:
{code}

Evaluation:
{evaluation}

Your Revised Code:
"""

@retry()
def generate(data):
    finished = False
    if os.path.isfile(data["output_file"]):
        with open(data["output_file"]) as f:
            for i in f.readlines():
                i = json.loads(i)
                if i['id'] == data["id"]:
                    finished = True
                    output = i["output"]
                    break
    
    if finished:
        return output

    if "generation_config" in data:
        stream = client.chat.completions.create(
            model=data["model"],
            messages=data["messages"],
            **data["generation_config"]
        )
    else:
        stream = client.chat.completions.create(
            model=data["model"],
            messages=data["messages"],
        )
    
    output_data = {
        "id": data["id"],
        "output": stream.to_dict(),
        "input": data
    }
    with open(data["output_file"], 'a') as f:
        f.write(json.dumps(output_data, ensure_ascii=False)+'\n')
    
    return output_data["output"]
    
def find_value(input_string):
    pattern = r'\(((?:[^()|]*\([^()]*\))*[^()|]*)\|((?:[^()|]*\([^()]*\))*[^()|]*)\)'
    matches = re.findall(pattern, input_string)

    values, evals = [], []
    for m in matches:
        pattern = re.compile(r'\-?\d+\.\d+|\-?\d+')
        tmp_score = pattern.findall(m[0])
        value = float(tmp_score[0])
        values.append(value)
        evals.append(m[1].strip())
    
    return values, evals

def evaluate(mid_file, question, code, error_desc, iter, answer_idx):
    content = prompt['evaluate_1'].format(question=question, code=code, error_desc=error_desc)
    data = {
            "id": f"iter_{iter}_answer_{answer_idx}_value_1",
            "model": 'gpt-4o-2024-11-20',
            "messages": [{"role": "user", "content": content}],
            "output_file": mid_file,
        }
    output = generate(data)['choices'][0]['message']['content']
    # return

    content2 = prompt['evaluate_2'].format(error_desc=error_desc)
    data = {
            "id": f"iter_{iter}_answer_{answer_idx}_value_2",
            "model": 'gpt-4o-2024-11-20',
            "messages": [{"role": "user", "content": content},
                         {"role": "assistant", "content": output},
                         {"role": "user", "content": content2}],
            "output_file": mid_file,
        }
    while True:
        output2 = generate(data)['choices'][0]['message']['content']
        values, evals = find_value(output2)
        if len(values)==1:
            break
        else:
            tmp = []
            with open(mid_file) as f:
                for i in f.readlines():
                    i = json.loads(i)
                    if i['id'] != f"iter_{iter}_answer_{answer_idx}_value_2":
                        tmp.append(i)
            with open(mid_file, 'w') as f:
                for i in tmp:
                    line = json.dumps(i, ensure_ascii=False)
                    f.write(line+'\n')
    return values[0], evals[0]

def solve(student_id, problem, example, max_iter=5, max_beam=2, subdir=None):
    if subdir is None:
        mid_dir = f'/Users/mccartney/Desktop/selected/{student_id}/depth_{max_iter}_beam_{max_beam}'
    else:
        mid_dir = f'/Users/mccartney/Desktop/selected/{student_id}/{subdir}/depth_{max_iter}_beam_{max_beam}'
    os.makedirs(mid_dir, exist_ok=True)
    mid_file = f'{mid_dir}/{problem["problem_id"]}.json'
    content = prompt['generate_initial_code'].format(eg_question=example['question'], eg_code=example['program'], question=problem['question'])
    data = {
            "id": "iter_0_generate_code",
            "model": 'gpt-4o-2024-11-20',
            "messages": [{"role": "user", "content": content}],
            "output_file": mid_file,
        }
    output = generate(data)

    answer = output['choices'][0]['message']['content']

    value, eval = evaluate(mid_file=mid_file, question=problem['question'], code=answer, error_desc=problem['generate_error_desc'], iter=0, answer_idx=0)

    Nodes_list = []
    root_node = Node(level=0, value=value, answer=answer, eval=eval)
    Nodes_list.append(root_node)
    current_node = root_node
    # return
    for i in range(max_iter):
        if current_node.value >= 0.9:
            break
        # if 'erfect' in current_node.answer[:20]:
        #     break
        content = prompt["refine"].format(eg_code=example['program'], question=problem['question'], error_desc=problem['generate_error_desc'], code=current_node.answer, evaluation=current_node.eval)
        data = {
                "id": f"iter_{i+1}_refine",
                "model": 'gpt-4o-2024-11-20',
                "messages": [{"role": "user", "content": content}],
                "output_file": mid_file,
                "generation_config": {"n": max_beam}
            }
        output = generate(data)

        refined_code = [j['message']['content'] for j in output['choices']]

        nodes = []
        for j, c in enumerate(refined_code):
            value, eval = evaluate(mid_file=mid_file, question=problem['question'], code=c, error_desc=problem['generate_error_desc'], iter=i+1, answer_idx=j)
            nodes.append(Node(level=i+1, value=value, answer=c, eval=eval))
        nodes = sorted(nodes, key=(lambda x: x.value), reverse=True)
        Nodes_list += nodes
        current_node = nodes[0]

    return problem['problem_id'], current_node, Nodes_list
        # answer = output['choices'][0]['message']['content']
        # new_answer = [f'answer at level {i+1} and {j}-th' for j in range(max_beam)]
        # value = [0, 1, 2, 3, 4]
        # nodes = [Node(level=i+1, value=v, answer=a) for a, v in zip(new_answer, value)]
        # nodes = sorted(nodes, key=(lambda x: x.value), reverse=True)
        # current_node = nodes[0]
        # Nodes_list += nodes
    
    # for i in Nodes_list:
    #     print(i.level, i.value, i.answer)
    # print(current_node.level, current_node.value, current_node.answer)

prompt['naive_generation'] = """Given a Python programming problem, you need to write code to solve it. Your code must meet the following requirements:
	1.	Based on the provided error descriptions, your code must include and perfectly reproduce these errors.
	2.	Given a student’s previous code, you can use the style of their historical code as a reference. 

Directly output your code. At the end of your code, please include <e> to indicate its completion.

-Real Data-
Student's Past Code:
{eg_code}

New Programming Problem:
{question}

Error Descriptions:
{error_desc}

Code:
"""
def solve_naive_prompt(student_id, problem, example):
    mid_dir = f'/Users/mccartney/Desktop/selected/{student_id}/naive_prompt'
    os.makedirs(mid_dir, exist_ok=True)
    mid_file = f'{mid_dir}/{problem["problem_id"]}.json'
    content = prompt['naive_generation'].format(eg_code=example['program'], question=problem['question'], error_desc=problem['generate_error_desc'])
    data = {
            "id": "naive_generate",
            "model": 'gpt-4o-2024-11-20',
            "messages": [{"role": "user", "content": content}],
            "output_file": mid_file,
        }
    output = generate(data)
    
    answer = output['choices'][0]['message']['content'].split('<e>')[0]
    return problem['problem_id'], answer

prompt['cot_generation'] = """Given a Python programming problem, you need to write code to solve it. Your code must meet the following requirements:
	1.	Based on the provided error descriptions, your code must include and perfectly reproduce these errors.
	2.	Given a student’s previous code, you can use the style of their historical code as a reference. 

-Real Data-
Student's Past Code:
{eg_code}

New Programming Problem:
{question}

Error Descriptions:
{error_desc}

Make a plan then write. Your output should be of the following format:

Plan:
Your plan here.

Code:
Your code here. At the end of your code, please include <e> to indicate its completion.
"""

def solve_cot_prompt(student_id, problem, example):
    mid_dir = f'/Users/mccartney/Desktop/selected/{student_id}/cot_prompt'
    os.makedirs(mid_dir, exist_ok=True)
    mid_file = f'{mid_dir}/{problem["problem_id"]}.json'
    content = prompt['cot_generation'].format(eg_code=example['program'], question=problem['question'], error_desc=problem['generate_error_desc'])
    data = {
            "id": "naive_generate",
            "model": 'gpt-4o-2024-11-20',
            "messages": [{"role": "user", "content": content}],
            "output_file": mid_file,
        }
    output = generate(data)

    answer = output['choices'][0]['message']['content']
    answer = answer.split('Code:')[-1].strip()
    answer = answer.split('<e>')[0].strip()
    return problem['problem_id'], answer